function updateEnemy(e,dt,target){if(!e.alive)return;const center=enemyCenter(e),distance=center.distanceTo(target.pos);if(distance>e.warn*2)return;const protectedArea=safeZone(target.pos);if(!protectedArea&&(distance<e.aggro||e.alert))e.alert=true;if(protectedArea||distance>e.warn*1.8)e.alert=false;const destination=e.alert?target.pos:e.origin;const delta=destination.clone().sub(e.g.position);if(e.flying){if(e.alert){const desired=distance>350?delta:V(Math.cos(combatTime+e.phase)*200,Math.sin(combatTime*.5)*30,Math.sin(combatTime+e.phase)*200);e.g.position.addScaledVector(desired.normalize(),dt*(e.type==='militaryShip'?90:75));const p=nearest(e.g.position),n=e.g.position.clone().sub(p.center).normalize();if(e.g.position.distanceTo(p.center)<p.r+160)e.g.position.copy(p.center).addScaledVector(n,p.r+160);const m=new THREE.Matrix4().lookAt(e.g.position,target.pos,UP);e.g.quaternion.slerp(new THREE.Quaternion().setFromRotationMatrix(m),dt*2);}else{e.g.position.copy(e.origin).add(V(Math.sin(combatTime*.08+e.phase)*55,Math.cos(combatTime*.11+e.phase)*15,Math.cos(combatTime*.08+e.phase)*55));e.g.rotation.y=combatTime*.03+e.phase;}}
else{const up=e.g.position.clone().sub(e.p.center).normalize(),frame=frameAt(e.g.position,e.p.center),flat=delta.addScaledVector(up,-delta.dot(up));if(e.alert&&distance>(e.beast?2.4:22)){const speed=e.beast?4.3:2.7,eye=e.g.position.clone().addScaledVector(up,1.8),next=moveActor(eye,flat.clone().normalize().multiplyScalar(speed*dt),{up,p:e.p,height:1.8,r:e.beast?.7:.38,ignore:e.g});e.g.position.copy(next.addScaledVector(up,-1.8));}const look=flat.applyQuaternion(frame.clone().invert());e.g.quaternion.copy(frame).multiply(new THREE.Quaternion().setFromAxisAngle(UP,Math.atan2(-look.x,-look.z)));const walk=e.alert?Math.sin(combatTime*(e.beast?9:5)+e.phase)*.42:Math.sin(combatTime*.8+e.phase)*.025;if(e.rig)animateHuman(e.rig,dt);e.g.userData.legs?.forEach((l,k)=>l.rotation.x=walk*(k%2?1:-1));}
if(e.alert&&combatTime>=e.shotAt){if(e.beast){if(distance<3.4){hurtPlayer(14);e.shotAt=combatTime+1.3;}}else if(distance<(e.flying?1200:85)){enemyFire(e,target);e.shotAt=combatTime+(e.flying?1.25:1.7);}}}
function randomAmbush(){if(combatTime<ambushAt)return;ambushAt=combatTime+120+combatRng()*120;const pos=controlledPosition();if(safeZone(pos)||boost||auto||enemies.filter(e=>e.alive&&e.g.position.distanceTo(pos)<3000).length>6)return;if(combatRng()>.20)return;ambushAt=combatTime+480;const air=atmosphereAt(pos);if(mode==='pilot'||eva){for(let j=0;j<2;j++){const dir=V(combatRng()-.5,.2,combatRng()-.5).normalize(),e=spawnEnemy('pirateShip',pos.clone().addScaledVector(dir,1500+j*200));e.alert=true;e.shotAt=combatTime+6;}}else{const p=air.p,q=frameAt(pos,p.center);for(let j=0;j<2;j++){const point=surfacePoint(pos.clone().add(V(65+j*10,0,45).applyQuaternion(q)),p,.1),e=spawnEnemy('raider',point,p);e.alert=true;e.shotAt=combatTime+6;}}toast('Sinais hostis próximos. Você pode enfrentar ou se afastar.');}
function updateCombat(dt){combatTime+=dt;updateCharacterCombat();damageFlash=Math.max(0,damageFlash-dt*.7);if(reloadUntil>0&&combatTime>=reloadUntil){const d=weaponDefs[equipped];if(d.mag){const needed=Math.min(d.mag-magazines[equipped],equipment.ammo);magazines[equipped]+=needed;equipment.ammo-=needed;}reloadUntil=0;}if(combatTime-lastHurt>8){suitShield=Math.min(50,suitShield+dt*4);shipShield=Math.min(140,shipShield+dt*10);}if(mode==='foot'&&weaponDefs[equipped].mag&&magazines[equipped]===0&&reloadUntil===0&&equipment.ammo>0)reloadWeapon();if(firing)firePlayer();const target=playerTarget();for(const e of enemies)updateEnemy(e,dt,target);updateProjectiles(dt);randomAmbush();}
function initCombatJobs(){if(jobDefs.some(d=>d[0]==='hunt'))return;jobDefs.push(['hunt','Controle de fauna','Enfrente três predadores hostis fora do porto.',1500],['bounty','Caçada a saqueadores','Neutralize três piratas em solo.',2000],['patrol','Interceptação orbital','Derrote dois caças militares hostis.',3200]);}
function acceptCombat(type){if(mission){toast('Conclua ou cancele o contrato atual.');return;}const port=atPort();if(!port){toast('Aceite o contrato em um porto ou central de missões.');return;}const def=jobDefs.find(d=>d[0]===type),p=port.p||planets[0],tag='combat-'+(++enemySerial);mission={type,combat:true,origin:destinations.indexOf(port),tag,kills:0,need:type==='patrol'?2:3,reward:def[3],label:def[1]};const stPos=(destinations.find(d=>d.station)?.pos.clone()||V(1800,2300,2400));const base=type==='patrol'?stPos.add(V(1400,900,-900)):p.center.clone().addScaledVector(V(type==='hunt'?.48:-.52,1,.32).normalize(),p.r+2);for(let j=0;j<mission.need;j++){const point=base.clone().add(type==='patrol'?V(j*140,0,j*180):V(j*8,0,j*5));spawnEnemy(type==='patrol'?'militaryShip':type==='hunt'?'animal':'raider',type==='patrol'?point:surfacePoint(point,p,.12),type==='patrol'?null:p,tag);}toast('Contrato de combate aceito. O HUD indica os alvos.');renderPanel('jobs');}
function completeCombat(){if(!atPort()){toast('Retorne a um porto para receber.');return;}if(mission.kills<mission.need){toast('Ainda há inimigos do contrato ativos.');return;}credits+=mission.reward;mission=null;save();toast('Contrato concluído. Pagamento recebido!');renderPanel('jobs');}
function clearCombatMission(){if(!mission?.combat)return;for(const e of enemies)if(e.tag===mission.tag&&e.alive){e.alive=false;e.g.visible=false;e.g.traverse(o=>o.userData.removed=true);}}
function combatGoal(){if(!mission?.combat)return null;const pos=controlledPosition(),targets=enemies.filter(e=>e.alive&&e.tag===mission.tag);if(targets.length){const e=targets.reduce((a,b)=>a.g.position.distanceTo(pos)<b.g.position.distanceTo(pos)?a:b);return {pos:enemyCenter(e),label:'ALVO · '+enemyName(e)};}const port=destinations.filter(d=>!d.gate&&d.kind!=='water').reduce((a,b)=>a.pos.distanceTo(pos)<b.pos.distanceTo(pos)?a:b);return {pos:port.pos,label:'RECEBER RECOMPENSA'};}


