let particleCloud=null;

function initEffects(){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(360*3),3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(360*3),3));geometry.setDrawRange(0,0);particleCloud=new THREE.Points(geometry,new THREE.PointsMaterial({vertexColors:true,size:.22,transparent:true,opacity:.9,depthWrite:false,toneMapped:false}));particleCloud.frustumCulled=false;scene.add(particleCloud);const dustGeo=new THREE.BufferGeometry(),arr=new Float32Array(120*3);for(let j=0;j<arr.length;j++)arr[j]=(combatRng()-.5)*70;dustGeo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));ambientDust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xc9e7cf,size:.10,transparent:true,opacity:.5,depthWrite:false}));ambientDust.frustumCulled=false;scene.add(ambientDust);}
function updateEffects(dt){if(particleCloud){for(let i=combatParticles.length-1;i>=0;i--){const p=combatParticles[i];p.life-=dt;if(p.life<=0){combatParticles.splice(i,1);continue;}p.pos.addScaledVector(p.v,dt);p.v.multiplyScalar(1-dt*.7);}const pos=particleCloud.geometry.attributes.position,col=particleCloud.geometry.attributes.color;combatParticles.forEach((p,j)=>{pos.setXYZ(j,p.pos.x,p.pos.y,p.pos.z);col.setXYZ(j,p.color.r,p.color.g,p.color.b);});pos.needsUpdate=true;col.needsUpdate=true;particleCloud.geometry.setDrawRange(0,combatParticles.length);particleCloud.material.size=mode==='pilot'?1.4:.19;particleCloud.visible=particlesEnabled;}for(let i=transientFX.length-1;i>=0;i--){const f=transientFX[i];f.life-=dt;if(typeof f.update==='function')f.update(dt,Math.max(0,f.life/f.ttl));f.o.material.opacity=Math.max(0,f.life/f.ttl*.7);if(f.r)f.o.scale.setScalar(.4+(1-f.life/f.ttl)*f.r);if(f.life<=0){scene.remove(f.o);f.o.geometry.dispose();f.o.material.dispose();transientFX.splice(i,1);}}if(ambientDust){const air=atmosphereAt(camera.position);ambientDust.visible=particlesEnabled&&air.p&&air.p.center&&air.alt<450&&!inside&&mode!=='pilot';if(ambientDust.visible){ambientDust.position.copy(camera.position);ambientDust.quaternion.copy(frameAt(camera.position,air.p.center));ambientDust.material.color.set(air.p.i===2?0xe1f1ff:air.p.i===3?0xc6a6e5:air.p.def[5]);ambientDust.material.size=air.p.i===2?.16:.08;ambientDust.geometry.setDrawRange(0,quality==='low'?40:120);const p=ambientDust.geometry.attributes.position;for(let j=0;j<p.count;j++){let y=p.getY(j)-dt*(air.p.i===2?1.7:.3);if(y< -35)y=35;p.setY(j,y);}p.needsUpdate=true;}}}
function loadEquipment(){try{const s=JSON.parse(localStorage.getItem('horizonte-v1'));if(s?.equipment){const x=s.equipment;equipment.weapons=[...new Set(['pistol','blade',...(Array.isArray(x.weapons)?x.weapons.filter(w=>['rifle','shotgun','sabre'].includes(w)):[])])];for(const key of ['ammo','grenades','medkits'])if(Number.isFinite(x[key]))equipment[key]=Math.max(0,Math.min(9999,Math.floor(x[key])));}}catch{}equipment.ships=[0];equipment.vehicles=['rover'];vehicleKind='rover';shipType=0;}
function bootV04(){loadEquipment();for(const a of animals)sculptAnimal(a.g,a.p.i);remodelRover();enhanceShip();initCombatJobs();initEnemies();initEffects();rebuildWeapon();bindTouch();setTouch(touchEnabled);applyQuality(quality);}
function v04Tick(dt,paused){if(!paused){updateCombat(dt);animateEntities(dt);updateEffects(dt);}updateCombatHud();const far=quality==='low'?2000:quality==='medium'?3500:5000;for(const e of enemies)e.g.visible=e.alive&&e.g.position.distanceTo(camera.position)<(e.flying?6500:1800);if(weaponView){if(equipped==='unarmed'){weaponView.visible=(unarmedRaiseBlend>0.005)&&mode==='foot'&&!paused&&!thirdPerson&&!resting;}else{weaponView.visible=mode==='foot'&&!paused&&!thirdPerson&&!resting;}}}


window.getGrenadeTrajectory = () => grenadeTrajectoryLine;

