const staticBodies=[],movingBodies=[];let collisionReady=false;
function belongsTo(obj,root){while(obj){if(obj===root)return true;obj=obj.parent;}return false;}
function makeBody(obj,bounds){if(!bounds){obj.geometry.computeBoundingBox();bounds=obj.geometry.boundingBox.clone();}return {obj,bounds,torus:obj.geometry?.type==='TorusGeometry'?obj.geometry.parameters:null,world:new THREE.Box3(),inv:new THREE.Matrix4(),scale:V(1,1,1)};}
function refreshBody(b){b.obj.updateWorldMatrix(true,false);b.inv.copy(b.obj.matrixWorld).invert();b.world.copy(b.bounds).applyMatrix4(b.obj.matrixWorld);b.obj.getWorldScale(b.scale);b.rotation=(b.rotation||b.obj.getWorldQuaternion(new THREE.Quaternion()));}

function surfacePoint(pos,p,offset=0){const n=pos.clone().sub(p.center).normalize();return p.center.clone().addScaledVector(n,radius(p,n)+offset);}
function upAt(pos){if(inside&&mode!=='pilot')return UP.clone().applyQuaternion(ship.quaternion);if(station&&pos.distanceTo(station.position)<160)return UP.clone();return pos.clone().sub(nearest(pos).center).normalize();}

function groundEye(pos,p,height=1.8){return surfacePoint(pos,p,height+.12);}
function supportEye(pos,up,p,height,bodies){const result=pos.clone(),feet=result.clone().addScaledVector(up,-height),stepUp=.35,stepDown=.30,origin=feet.clone().addScaledVector(up,stepUp);let best=null,bestHeight=-Infinity;const ray=new THREE.Raycaster(origin,up.clone().negate(),0,stepUp+stepDown);ray.layers.enable(31);const candidates=bodies.filter(b=>b.obj.isMesh&&!b.obj.userData.noSupport&&!hasAncestorFlag(b.obj,'actor')&&!hasAncestorFlag(b.obj,'dynamic')&&!b.obj.userData.removed).map(b=>b.obj);for(const hit of ray.intersectObjects(candidates,false)){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);if(Math.abs(normal.dot(up))<.55)continue;const eye=hit.point.clone().addScaledVector(up,height+.04),difference=eye.clone().sub(result).dot(up);if(difference<=stepUp+.05&&difference>=-stepDown&&difference>bestHeight){best=eye;bestHeight=difference;}}if(p){const terrain=groundEye(result,p,height),difference=terrain.clone().sub(result).dot(up);if(difference<=stepUp&&difference>=-stepDown&&difference>bestHeight)best=terrain;}return best||result;}

function spherePush(center,r,b){if(b.obj.userData.surfaceOnly)return null;if(b.obj.userData.thinPanel)return thinPanelPush(center,r,b);if(b.torus){const local=center.clone().applyMatrix4(b.inv),len=Math.hypot(local.x,local.y),nearest=V(b.torus.radius*(len?local.x/len:1),b.torus.radius*(len?local.y/len:0),0),d=local.clone().sub(nearest),distance=d.length();if(distance>=b.torus.tube+r)return null;if(distance<.001)d.set(0,0,1);else d.divideScalar(distance);return d.multiplyScalar(b.torus.tube+r-distance+.002).applyQuaternion((b.rotation||b.obj.getWorldQuaternion(new THREE.Quaternion())));}const c=center.clone().applyMatrix4(b.inv),rr=V(r/Math.abs(b.scale.x),r/Math.abs(b.scale.y),r/Math.abs(b.scale.z)),closest=c.clone().clamp(b.bounds.min,b.bounds.max),d=c.clone().sub(closest);if(d.lengthSq()>0){const worldD=d.clone().multiply(b.scale),length=worldD.length();if(length>=r)return null;return worldD.normalize().multiplyScalar(r-length+.002).applyQuaternion((b.rotation||b.obj.getWorldQuaternion(new THREE.Quaternion())));}const faces=[['x',b.bounds.max.x-c.x+rr.x,1],['x',c.x-b.bounds.min.x+rr.x,-1],['y',b.bounds.max.y-c.y+rr.y,1],['y',c.y-b.bounds.min.y+rr.y,-1],['z',b.bounds.max.z-c.z+rr.z,1],['z',c.z-b.bounds.min.z+rr.z,-1]].sort((a,z)=>a[1]*Math.abs(b.scale[a[0]])-z[1]*Math.abs(b.scale[z[0]]));const f=faces[0],push=V();push[f[0]]=(f[1]+.002)*f[2]*b.scale[f[0]];return push.applyQuaternion((b.rotation||b.obj.getWorldQuaternion(new THREE.Quaternion())));}
function moveActor(eye,delta,{up=UP,p=null,height=1.8,r=.36,ignore=null,grounded=true}={}){let pos=eye.clone(),steps=Math.max(1,Math.min(800,Math.ceil(delta.length()/.22))),step=delta.clone().divideScalar(steps),bodies=nearbyBodies(eye,delta.length()+height+4,ignore);for(let j=0;j<steps;j++){pos.add(step);if(grounded)pos=supportEye(pos,up,p,height,bodies);for(let pass=0;pass<3;pass++){let changed=false;for(const b of bodies){if(b.world.distanceToPoint(pos)>height+r+1)continue;for(const h of [r,height/2,height-r]){const center=pos.clone().addScaledVector(up,h-height),push=spherePush(center,r,b);if(push){pos.add(push);changed=true;}}}if(!changed)break;}}return pos;}
function moveGround(eye,delta,p,ignore=null,height=1.8,r=.36){const up=station&&eye.distanceTo(station.position)<160?UP.clone():eye.clone().sub(p.center).normalize();return moveActor(eye,delta,{up,p:station&&eye.distanceTo(station.position)<160?null:p,ignore,height,r});}

function safeExit(around,root,p){const q=root.getWorldQuaternion(new THREE.Quaternion());for(const off of [V(3,0,0),V(-3,0,0),V(0,0,5),V(0,0,-5)]){let eye=around.clone().add(off.applyQuaternion(q));eye=placeOnGround(eye,p);const fixed=moveActor(eye,V(),{up:p?eye.clone().sub(p.center).normalize():UP,p,ignore:root});if(fixed.distanceTo(eye)<.3)return fixed;}return placeOnGround(around.clone().add(V(0,0,6)),p);}

