function equipWeapon(id){if(id!=='tool'&&id!=='grenade'&&id!=='unarmed'&&!equipment.weapons.includes(id))return equipWeaponBase(id);equipWeaponBase(id);if(equipped!==id)return;if(!cyclingEquipment)recentEquipment=[id,...recentEquipment.filter(x=>x!==id)].slice(0,3);if(!aimCapable()){aiming=false;aimOwner=null;}save();}
function cycleWeapon(){
  const list=recentEquipment.filter(id=>{
    if(id==='grenade') return equipment.grenades>0;
    if(id==='tool'||id==='unarmed') return true;
    return equipment.weapons.includes(id);
  });
  if(!list.length)return;
  cyclingEquipment=true;
  equipWeapon(list[(list.indexOf(equipped)+1)%list.length]);
  cyclingEquipment=false;
}
function hideWeaponInfo(){const e=$('equipmentInfo');if(e)e.classList.add('hidden');weaponInfoHeld=false;}
function showWeaponInfo(id){const d=weaponDefs[id];$('equipmentInfo').innerHTML=`<strong>${d.name}</strong><p>${id==='unarmed'?'Combate desarmado. Desfere socos rápidos com mãos alternadas.':id==='tool'?'Coleta minério, cataloga fauna e executa ações de contratos.':id==='grenade'?'Explosão em área. Mantenha distância.':d.mag?'Arma de longo alcance. Segure à direita para mirar.':'Arma de combate próximo.'}</p><p>${d.damage?d.damage+' de dano · ':''}${d.range} m${d.mag?' · carregador de '+d.mag:''}</p>`;$('equipmentInfo').classList.remove('hidden');}
function showWeaponPicker(){pendingTaps.left=pendingTaps.right=null;$('actionStrip').classList.add('hidden');const ids=[...new Set([...equipment.weapons,...(equipment.grenades>0?['grenade']:[]),'tool','unarmed'])];$('weaponPicker').innerHTML='<div class="pickerTitle">EQUIPAMENTO <span>Toque escolhe · segure para detalhes</span></div><div class="equipmentGrid">'+ids.map(id=>`<div role="button" tabindex="0" class="equipmentItem ${id===equipped?'selected':''}" data-equipment="${id}"><strong>${weaponDefs[id].name}</strong><small>${recentEquipment.includes(id)?'ACESSO RÁPIDO':'SELECIONAR'}</small></div>`).join('')+'</div>';$('weaponPicker').classList.remove('hidden');for(const el of $('weaponPicker').querySelectorAll('[data-equipment]')){const id=el.dataset.equipment;el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();el.setPointerCapture(e.pointerId);weaponItemPress={id,pointerId:e.pointerId,at:inputNow(),x:e.clientX,y:e.clientY,held:false,moved:false};});el.addEventListener('pointermove',e=>{if(weaponItemPress?.pointerId===e.pointerId&&Math.hypot(e.clientX-weaponItemPress.x,e.clientY-weaponItemPress.y)>14)weaponItemPress.moved=true;});el.addEventListener('pointerup',e=>endEquipmentItem(e,false));el.addEventListener('pointercancel',e=>endEquipmentItem(e,true));el.addEventListener('lostpointercapture',e=>endEquipmentItem(e,true));el.addEventListener('keydown',e=>{if(e.key==='Enter'){equipWeapon(id);closeWeaponPicker();}});}}
function endEquipmentItem(e,cancel){const t=weaponItemPress;if(!t||t.pointerId!==e.pointerId)return;e.preventDefault?.();advanceTouch(inputNow());const choose=!cancel&&!t.held&&!t.moved;weaponItemPress=null;hideWeaponInfo();if(choose){equipWeapon(t.id);closeWeaponPicker();}}
function closeWeaponPicker(){$('weaponPicker').classList.add('hidden');hideWeaponInfo();weaponItemPress=null;}
function bindWeaponButton(){const b=$('quickWeapon');if(!b)return;b.addEventListener('pointerdown',e=>{if(mode==='rover')return;e.preventDefault();e.stopPropagation();b.setPointerCapture(e.pointerId);weaponPress={pointerId:e.pointerId,at:inputNow(),x:e.clientX,y:e.clientY,moved:false,held:false,reloaded:false};});b.addEventListener('pointermove',e=>{const p=weaponPress;if(!p||p.pointerId!==e.pointerId)return;const r=b.getBoundingClientRect(),outside=e.clientX<r.left||e.clientX>r.left+r.width||e.clientY<r.top||e.clientY>r.top+r.height;if(!p.held&&outside&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>16){p.moved=true;if(!p.reloaded){p.reloaded=true;if(mode==='foot')reloadWeapon();}}});b.addEventListener('pointerup',e=>{const p=weaponPress;if(!p||p.pointerId!==e.pointerId)return;e.preventDefault();advanceTouch(inputNow());weaponPress=null;if(!p.held&&!p.moved){

    if(!$('weaponPicker').classList.contains('hidden'))closeWeaponPicker();
    else cycleWeapon();
  }});for(const type of ['pointercancel','lostpointercapture'])b.addEventListener(type,e=>{if(weaponPress?.pointerId===e.pointerId)weaponPress=null;});}
function contextualActions(){const a=[['camera',thirdPerson?'1ª pessoa':'3ª pessoa']];if(mode==='pilot'){a.push(['seat','Levantar'],['boarding','Desembarcar'],['ramp','Rampa'],['land','Pousar [F]'],['brake','Frear'],['headlights',shipHeadlightsActive?'Faróis: Ligados [L]':'Faróis: Desligados [L]']);if(auto)a.push(['manual','Voo manual']);}else if(mode==='rover'){a.push(['seat','Sair do veículo'],['boarding','Embarcar veículo'],['recall','Voltar à nave']);}else{a.push(['interact','Interagir'],['tool','Ferramenta'],['medkit','Kit médico'],['recall','Voltar à nave']);if(inside||controlledPosition().distanceTo(entryWorld())<12)a.push(['boarding',inside?'Desembarcar':'Embarcar'],['ramp','Rampa']);}return a;}
function refreshActionStrip(){const actions=contextualActions(),signature=JSON.stringify(actions);if(signature===stripSignature)return;stripSignature=signature;$('actionStrip').innerHTML=actions.map(([id,label])=>`<button onclick="runContextAction('${id}')">${label}</button>`).join('');}
function toggleActionStrip(){pendingTaps.left=pendingTaps.right=null;closeWeaponPicker();$('actionStrip').classList.toggle('hidden');stripSignature='';refreshActionStrip();}
function runContextAction(id){if(!contextualActions().some(a=>a[0]===id))return;$('actionStrip').classList.add('hidden');const actions={camera:toggleCamera,map:()=>menu('map'),inventory:()=>menu('inventory'),jobs:()=>menu('jobs'),fleet:()=>menu('fleet'),seat:leaveSeatGesture,interact,boarding:boardingAction,ramp:toggleRamp,land,brake:brakeShip,manual:()=>auto=null,recall,tool:()=>equipWeapon('tool'),medkit:useMedkit,guide:toggleGuide,audio:toggleAudio,headlights:cycleHeadlightMode};actions[id]?.();}
function bootV06(){try{const saved=JSON.parse(localStorage.getItem('horizonte-v1'))?.skyward?.recentEquipment;if(Array.isArray(saved)){const valid=[...new Set(saved.filter(id=>weaponDefs[id]&&(equipment.weapons.includes(id)||id==='grenade'||id==='tool'||id==='unarmed')))];if(valid.length)recentEquipment=valid.slice(0,3);}}catch{}gestureMode=gestureContext();}

