function city(parent,p){if(p)decoratePlanet(parent,p);else stationCity(parent,p);}
function settlementNormals(p){if(p.siteNormals)return p.siteNormals;const v=(typeof settlementProfiles!=='undefined'&&settlementProfiles[p.i])?settlementProfiles[p.i]:{cities:0,villages:0};const out=[];if(v.cities||v.villages)out.push({n:UP.clone(),half:v.cities?285:130});if(v.cities>1)out.push({n:V(.85,.15,-.48).normalize(),half:285});for(let i=v.cities?0:1;i<v.villages;i++){const a=1.6+i*2.1+p.i*.3;out.push({n:V(Math.cos(a)*.8,-.25,Math.sin(a)*.8).normalize(),half:130});}p.siteNormals=out;return out;}
function radius(p,n){
window.radius = radius;
  let value=height(n,p.i)-waterCarve(p,n);
  for(const site of settlementNormals(p)){
    const distance=Math.acos(THREE.MathUtils.clamp(n.dot(site.n),-1,1))*p.r,blend=THREE.MathUtils.smoothstep(distance,site.half-35,site.half);
    const minElev=(typeof wetPlanet==='function'&&wetPlanet(p))?Math.max(14,seaRadius(p)-p.r+14,height(site.n,p.i)):Math.max(8,height(site.n,p.i));
    if(blend<1)value=THREE.MathUtils.lerp(minElev,value,blend);
  }
  return p.r+value;
}
function walkFrame(pos,p){if(station&&pos.distanceTo(station.position)<180)return station.getWorldQuaternion(new THREE.Quaternion());return p?frameAt(pos,p.center):new THREE.Quaternion();}
function placeOnGround(pos,p,height=1.8){const baseline=p?groundEye(pos,p,height):pos.clone(),up=p?planetUp(pos,p):UP.clone();const floor=floorProbe(baseline.clone().addScaledVector(up,2),up,p,height,5);return floor||baseline;}
function safeZone(pos){return settlements.some(s=>pos.distanceTo(s.center)<s.half*1.5)||destinations.some(d=>d.station&&pos.distanceTo(d.pos)<175);}
// atPort defined in 05_math_and_helpers.js
function registerBodies(){staticBodies.length=0;movingBodies.length=0;scene.updateMatrixWorld(true);scene.traverse(o=>{if(!o.isMesh||hasAncestorFlag(o,'noCollision')||hasAncestorFlag(o,'actor')||hasAncestorFlag(o,'dynamic')||hasAncestorFlag(o,'combatEnemy')||o.geometry.type==='PlaneGeometry'&&!o.userData.surfaceOnly||o.geometry.type==='RingGeometry'||o.material.type==='ShaderMaterial'||o.userData.celestial||belongsTo(o,ship)||belongsTo(o,rover)||animals.some(a=>belongsTo(o,a.g)))return;const b=makeBody(o);refreshBody(b);staticBodies.push(b);});refreshMovingBodies();collisionReady=true;}

function updateCitizens(dt,paused){if(paused)return;const observer=controlledPosition(),nearby=npcs.filter(n=>{const s=n.settlement||n.shop?.settlement;return (!s||s.center.distanceTo(observer)<s.half+210)&&n.g.getWorldPosition(V()).distanceTo(observer)<(quality==='low'?110:175)});for(const n of nearby){const near=n.g.getWorldPosition(V()).distanceTo(observer)<3.2;if(n.settlement){n.walkPhase=(n.walkPhase||0)+(near?0:dt*.0013);const local=townPath(n.settlement,n.walkPhase,1.075),ahead=townPath(n.settlement,n.walkPhase+.002,1.075),world=settlementPoint(n.settlement,local.x,local.z,.18);n.city.position.copy(world).sub(n.settlement.root.position);n.city.quaternion.copy(frameAt(world,n.settlement.p.center));const d=ahead.sub(local);n.g.rotation.y=Math.atan2(-d.x,-d.z);}else{if(n.wait>0)n.wait-=dt;if(!near&&n.wait<=0){const delta=n.path[n.way].clone().sub(n.g.position),dist=delta.length();if(dist<.12){n.way=(n.way+1)%n.path.length;n.wait=1.5;}else n.g.position.addScaledVector(delta.normalize(),Math.min(dist,dt*.85));}if(near){const d=n.city.worldToLocal(observer.clone()).sub(n.g.position);n.g.rotation.y=Math.atan2(-d.x,-d.z);}}if(!n.proxy?.visible)animateHuman(n.g,dt);}for(const a of animals){if(a.g.position.distanceTo(observer)>250)continue;const q=frameAt(a.origin,a.p.center),offset=V(Math.sin(totalTime*.25+a.phase)*2.5,0,Math.cos(totalTime*.25+a.phase)*2.5).applyQuaternion(q),candidate=a.origin.clone().add(offset);if(candidate.distanceTo(observer)>3.5&&!isWater(a.p,planetUp(candidate,a.p)))a.g.position.copy(candidate);a.g.position.copy(surfacePoint(a.g.position,a.p,.1));a.g.quaternion.copy(frameAt(a.g.position,a.p.center));}}
function planetApproach(d,air){const n=planetUp(ship.position,air.p),targetN=planetUp(d.pos,d.p),angle=planetUp(ship.position,d.p.center?d.p:air.p).angleTo(targetN);if(air.p!==d.p&&air.alt<ATMOSPHERE+200)return air.p.center.clone().addScaledVector(n,air.p.r+ATMOSPHERE+450);if(angle>.09){const own=planetUp(ship.position,d.p),step=own.clone().lerp(targetN,.2).normalize();if(own.dot(targetN)<-.94)step.copy(own).add(V(.3,.1,.2)).normalize();return d.p.center.clone().addScaledVector(step,d.p.r+1000);}return d.pos.clone().addScaledVector(targetN,2);}
