let audioContext=null,musicBus,fxBus,masterBus,engineGain,engineOsc,engineFilter,windGain,audioMuted=false,nextChord=0,nextMelody=0,musicStep=0,footTimer=0,musicVolume=.35,fxVolume=.6;
function tone(freq,time,duration,gain,bus,type='sine',pan=0){if(!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain(),p=audioContext.createStereoPanner();o.type=type;o.frequency.value=freq;p.pan.value=pan;const attack=Math.min(0.06,Math.max(0.005,duration*0.35));g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime(gain,time+attack);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g).connect(p).connect(bus);o.start(time);o.stop(time+duration+.1);o.onended=()=>{o.disconnect();g.disconnect();p.disconnect()};}
function initAudio(){if(audioContext){audioContext.resume();return;}try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioContext=new AC();masterBus=audioContext.createGain();masterBus.gain.value=.7;const limiter=audioContext.createDynamicsCompressor();masterBus.connect(limiter).connect(audioContext.destination);musicBus=audioContext.createGain();musicBus.gain.value=musicVolume;musicBus.connect(masterBus);fxBus=audioContext.createGain();fxBus.gain.value=fxVolume;fxBus.connect(masterBus);
const delay=audioContext.createDelay(2),feedback=audioContext.createGain();delay.delayTime.value=.57;feedback.gain.value=.23;musicBus.connect(delay);delay.connect(feedback);feedback.connect(delay);feedback.connect(masterBus);
engineOsc=audioContext.createOscillator();engineOsc.type='sawtooth';engineFilter=audioContext.createBiquadFilter();engineFilter.type='lowpass';engineFilter.frequency.value=150;engineGain=audioContext.createGain();engineGain.gain.value=0;engineOsc.connect(engineFilter).connect(engineGain).connect(fxBus);engineOsc.start();const buffer=audioContext.createBuffer(1,audioContext.sampleRate*2,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const noise=audioContext.createBufferSource();noise.buffer=buffer;noise.loop=true;const windFilter=audioContext.createBiquadFilter();windFilter.type='lowpass';windFilter.frequency.value=650;windGain=audioContext.createGain();windGain.gain.value=0;noise.connect(windFilter).connect(windGain).connect(fxBus);noise.start();nextChord=audioContext.currentTime+.1;nextMelody=audioContext.currentTime+3;audioContext.resume();}catch(e){if(audioContext)audioContext.close().catch(()=>{});audioContext=null;$('audioStatus').textContent='Áudio indisponível neste navegador';}}
function toggleAudio(){initAudio();audioMuted=!audioMuted;if(masterBus)masterBus.gain.setTargetAtTime(audioMuted?0:.7,audioContext.currentTime,.08);$('audioToggle').textContent='U · ÁUDIO '+(audioMuted?'OFF':'ON');}
function setVolume(type,value){initAudio();const n=Number(value)/100;if(type==='music'){musicVolume=n;if(musicBus)musicBus.gain.setTargetAtTime(n,audioContext.currentTime,.05);}else{fxVolume=n;if(fxBus)fxBus.gain.setTargetAtTime(n,audioContext.currentTime,.05);}}
function soundCue(text){if(!audioContext)return;const t=audioContext.currentTime;if(/Teletransporte/.test(text)){[220,330,440,660,880].forEach((f,i)=>tone(f,t+i*.055,.35,.09,fxBus));}else if(/coletado|catalogada|Pagamento/.test(text)){[523,659,784].forEach((f,i)=>tone(f,t+i*.09,.4,.07,fxBus));}else if(/Rampa|Decolagem|Chegada/.test(text)){tone(110,t,.7,.08,fxBus,'triangle');tone(220,t+.12,.5,.06,fxBus);}else tone(480,t,.13,.025,fxBus);}
function updateAudio(dt,paused){if(!audioContext||audioContext.state!=='running')return;const t=audioContext.currentTime;windGain.gain.setTargetAtTime(paused?0:boost?.16:heat>.1?heat*.12:eva?.016:inside?.002:.028,t,.2);const aboard=inside||mode==='pilot',intensity=landed?.025:Math.min(.15,.04+Math.abs(flightSpeed)/20000);engineGain.gain.setTargetAtTime(paused?0:aboard?intensity:eva?.012:.006,t,.25);engineOsc.frequency.setTargetAtTime(landed?35:45+Math.min(100,Math.abs(flightSpeed)/20),t,.2);engineFilter.frequency.setTargetAtTime(landed?100:200+Math.min(600,Math.abs(flightSpeed)/4),t,.3);
if(t>=nextChord){const chords=[[130.81,164.81,196,246.94],[110,164.81,220,261.63],[87.31,130.81,174.61,220],[98,146.83,196,293.66],[130.81,196,261.63,329.63],[110,164.81,246.94,329.63]];chords[musicStep%chords.length].forEach((f,i)=>tone(f,t+.04*i,9,.04,musicBus,'sine',(i-1.5)*.4));musicStep++;nextChord=t+9+(musicStep%3);}
if(t>=nextMelody){const scale=[261.63,293.66,329.63,392,440,523.25,659.25],index=(musicStep*3+Math.floor(totalTime/4))%scale.length;tone(scale[index],t,2.8,.032,musicBus,'triangle',Math.sin(totalTime)*.5);nextMelody=t+2.5+(musicStep%4)*.8;}
if(!paused&&mode==='foot'&&!eva&&(Math.abs(axisForward())>.05||Math.abs(axisStrafe())>.05)){footTimer-=dt;if(footTimer<=0){tone(inside?100:75,t,.1,.065,fxBus,'triangle');footTimer=keys.ShiftLeft?.27:.43;}}}
// boardingAction defined in 05_math_and_helpers.js
window.recall=recall;window.toggleGuide=toggleGuide;window.updateGuide=updateGuide;window.toggleAudio=toggleAudio;window.setVolume=setVolume;
